################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd_ex.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc_ex.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi_ex.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c \
/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_usb.c 

OBJS += \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_cortex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_gpio.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pcd.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pcd_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rtc.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rtc_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_spi.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_spi_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_ll_usb.o 

C_DEPS += \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_cortex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_gpio.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pcd.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pcd_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rtc.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rtc_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_spi.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_spi_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_ll_usb.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_cortex.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_gpio.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c_ex.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pcd.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pcd_ex.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr_ex.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc_ex.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rtc.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rtc_ex.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_spi.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_spi_ex.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim_ex.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_ll_usb.o: /Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_usb.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DOSX_BMS_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/CMSIS/Include" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/Common" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/hts221" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm6dsm" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lps22hb" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/lsm303agr" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/Components/stc3115" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Drivers/BSP/SensorTile" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/Third_Party/FatFs/src/drivers" -I"/Users/charleszaloom/Downloads/EmbeddedML_SensorTile_Introduction/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I/Users/wkaiser/Documents/Primary/Courses/ST_Microelectronics_IoT/Development/SensorTile_Inertial_Sensing/Reference_System_2-21-2019/SensorTile_Inertial_Sensing -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019 -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Demonstation_Project_5_31_2019/EmbeddedML_SensorTile_Introduction/Projects/SensorTile/Applications/DataLog/Src -I/Users/wkaiser/Documents/Primary/Courses/Embedded_ML/Embedded_ML_Development_XOR_AND/Embedded_ML_XOR-AND_V2  -O0 -g1 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


